
dataset: LOLv2

#### datasets
datasets:
  train:
    root: 
    use_shuffle: true
    n_workers: 1  
    batch_size: 8
    use_flip: true
    use_crop: true
    GT_size: 96 

  val:
    root: 
    n_workers: 1
    use_crop: true
    batch_size: 1 



